{
  "id" => 8289, 
  "name" => "Full Tank Dont Dead ", 
  "build_type" => "PvP", 
  "level" => 60, 
  "constitution" => 88, 
  "strength" => 112, 
  "dexterity" => 5, 
  "intelligence" => 5, 
  "focus" => 5, 
  "created_at" => "2021-09-11T19:51:05.643Z", 
  "updated_at" => "2021-09-11T19:51:05.643Z", 
  "user_id" => 10747, 
  "description" => {
    "id" => nil, 
    "name" => "description", 
    "body" => nil, 
    "record_type" => "Build", "record_id" => 8289, 
    "created_at" => nil, 
    "updated_at" => nil
  }, 
  "votes" => nil, 
  "category" => nil, 
  "amulet_gem" => nil, 
  "ring_gem" => nil, 
  "earring_gem" => nil, 
  "weapon1_ability1" => 1059, 
  "weapon1_ability2" => 1056, 
  "weapon1_ability3" => 1062, 
  "weapon2_ability1" => 1075, 
  "weapon2_ability2" => 1098, 
  "weapon2_ability3" => 1101, 
  "weapon3_ability1" => nil, 
  "weapon3_ability2" => nil, 
  "weapon3_ability3" => nil, 
  "weapon1_abilities" => [1047, 1049, 1059, 1065, 1066, 1068, 1067, 1056, 1069, 1062, 1060, 1070, 1057, 1071, 1072, 1063, 1073, 1061, 1074], 
  "weapon2_abilities" => [1087, 1075, 1076, 1089, 1077, 1092, 1090, 1104, 1105, 1098, 1099, 1100, 1108, 1101, 1107, 1110, 1102, 1103, 1112], 
  "weapon3_abilities" => nil, 
  "slug" => "full-tank-dont-dead-c6c693", 
  "tier" => nil, 
  "weapon1_id" => 11432, 
  "weapon2_id" => 24150, 
  "weapon3_id" => nil, 
  "offhand1_id" => nil, 
  "offhand2_id" => nil, 
  "offhand3_id" => nil, 
  "weapon1_perk1_id" => 1478, 
  "weapon1_perk2_id" => 1612, 
  "weapon1_perk3_id" => 1720, 
  "weapon2_perk1_id" => 1502, 
  "weapon2_perk2_id" => 1580, 
  "weapon2_perk3_id" => 1850, 
  "weapon3_perk1_id" => nil, 
  "weapon3_perk2_id" => nil, 
  "weapon3_perk3_id" => nil, 
  "weapon1_gem_id" => nil, 
  "weapon2_gem_id" => nil, 
  "weapon3_gem_id" => nil, 
  "offhand1_perk1_id" => nil, 
  "offhand1_perk2_id" => nil, 
  "offhand1_perk3_id" => nil, 
  "offhand2_perk1_id" => nil, 
  "offhand2_perk2_id" => nil, 
  "offhand2_perk3_id" => nil, 
  "offhand3_perk1_id" => nil, 
  "offhand3_perk2_id" => nil, 
  "offhand3_perk3_id" => nil, 
  "offhand1_gem_id" => nil, 
  "offhand2_gem_id" => nil, 
  "offhand3_gem_id" => nil, 
  "head_id" => 24671, 
  "head_perk1_id" => 1452, 
  "head_perk2_id" => 1600, 
  "head_perk3_id" => 1733, 
  "head_gem_id" => nil, 
  "chest_id" => 24672,
  "chest_perk1_id" => 1452, 
  "chest_perk2_id" => 1608, 
  "chest_perk3_id" => 1733, 
  "chest_gem_id" => nil, 
  "hands_id" => 24669, 
  "hands_perk1_id" => 1452, 
  "hands_perk2_id" => 1600, 
  "hands_perk3_id" => 1733, 
  "hands_gem_id" => nil, 
  "legs_id" => 24670, 
  "legs_perk1_id" => 1452, 
  "legs_perk2_id" => 1612, 
  "legs_perk3_id" => 1733, 
  "legs_gem_id" => nil, 
  "feet_id" => 24673, 
  "feet_perk1_id" => 1452, 
  "feet_perk2_id" => 1612, 
  "feet_perk3_id" => 1733, 
  "feet_gem_id" => nil, 
  "amulet_id" => 24789, 
  "ring_id" => 24801, 
  "earring_id" => 24866, 
  "is_featured" => nil, 
  "is_meta" => nil, 
  "weight_class" => "heavy", 
  "author_name" => "NiTzell", 
  "game_version" => "beta", 
  "weapon1_type" => "Sword", 
  "weapon2_type" => "WarHammer", 
  "like_builds_count" => 1, 
  "is_private" => false, 
  "weapon1_perk4_id" => 1716, 
  "weapon1_perk5_id" => 1845, 
  "weapon2_perk4_id" => 1678, 
  "weapon2_perk5_id" => 1862, 
  "head_perk4_id" => 1781, 
  "head_perk5_id" => 1767, 
  "chest_perk4_id" => 1781, 
  "chest_perk5_id" => 1767, 
  "hands_perk4_id" => 1781, 
  "hands_perk5_id" => 1767, 
  "legs_perk4_id" => 1781, 
  "legs_perk5_id" => 1767, 
  "feet_perk4_id" => 1781, 
  "feet_perk5_id" => 1767, 
  "amulet_perk4_id" => 1784, 
  "amulet_perk5_id" => 1803, 
  "earring_perk4_id" => 1828, 
  "earring_perk5_id" => 1833, 
  "ring_perk4_id" => 1822, 
  "ring_perk5_id" => 1813, 
  "shield_id" => 24014, 
  "shield_perk1_id" => 1477, 
  "shield_perk2_id" => 1883, 
  "shield_perk3_id" => 1876, 
  "shield_perk4_id" => 1734, 
  "shield_perk5_id" => 1865, 
  "amulet_perk1_id" => 1452, 
  "amulet_perk2_id" => 1588, 
  "amulet_perk3_id" => 1794, 
  "earring_perk1_id" => 1452, 
  "earring_perk2_id" => 1584, 
  "earring_perk3_id" => 1827, 
  "ring_perk1_id" => 1452, 
  "ring_perk2_id" => 1568, 
  "ring_perk3_id" => 1820, 
  "weapon1_gear_score_override" => 600, 
  "weapon2_gear_score_override" => 600, 
  "shield_gear_score_override" => 600, 
  "head_gear_score_override" => 600, 
  "chest_gear_score_override" => 600, 
  "hands_gear_score_override" => 600, 
  "legs_gear_score_override" => 600, 
  "feet_gear_score_override" => 600, 
  "amulet_gear_score_override" => 600, 
  "earring_gear_score_override" => 600, 
  "ring_gear_score_override" => 500, 
  "build_stats" => {
    "weapon1" => 709, 
    "weapon2" => 997, 
    "shield" => nil, 
    "weight" => 36.8, 
    "weight_class" => "heavy", 
    "armor" => {
      "phys" => 2214, 
      "elem" => 1498
    }
  }, 
  "strength_gear" => 12, 
  "dexterity_gear" => 0, 
  "intelligence_gear" => 0, 
  "focus_gear" => 0, 
  "constitution_gear" => 212,
  "weapon1_ability_trees" => {
    "defender" => [
      {
        "id" => 1066,
        "weapon_tag" => "Sword",
        "ability_type" => "passive",
        "ability_id" => "Passive_Sword_Defender_MeleeBlock",
        "name" => "Sturdy Grip",
        "description" => "Stamina damage is reduced by 15.0% when blocking a melee attack with a shield.",
        "tree_row_position" => 0,
        "tree_column_position" => 3,
        "tree_name" => "defender",
        "required_ability_id" => "",
        "icon" => "Rapier_Ability4Mod1_Insult_to_Injury",
        "slug" => "sturdy-grip-318186",
        "cooldown_id" => "",
        "parsed_description" => "Stamina damage is reduced by 15.0% when blocking a melee attack with a shield.",
        "cooldown_time" => nil,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/rapier_ability4mod1_insult_to_injury.png"
      }, 
      {
        "id" => 1056,
        "weapon_tag" => "Sword",
        "ability_type" => "active",
        "ability_id" => "Ability_Sword_Bash",
        "name" => "Shield Bash",
        "description" => "Deals 50.0% weapon damage and stuns foes in front of you for 2.0s.  <br/> <br/>Taunt Gem Compatible: If you have a Carnelian gem equiped in your sword, This ability cause a 6s taunt to all enemies hit. (Taunt causes monsters to focus only on you.)",
        "tree_row_position" => 1,
        "tree_column_position" => 0,
        "tree_name" => "defender",
        "required_ability_id" => "",
        "icon" => "swordAbility4",
        "slug" => "shield-bash-9d2619",
        "cooldown_id" => "Ability_Sword_Bash",
        "parsed_description" => "Deals 50.0% weapon damage and stuns foes in front of you for 2.0s.  <br/> <br/>Taunt Gem Compatible: If you have a Carnelian gem equiped in your sword, This ability cause a 6s taunt to all enemies hit. (Taunt causes monsters to focus only on you.)",
        "cooldown_time" => 25,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/swordability4.png"
      }, 
      {
        "id" => 1063,
        "weapon_tag" => "Sword",
        "ability_type" => "upgrade",
        "ability_id" => "Upgrade_Sword_FinalStand_ArmorAboveHalf",
        "name" => "Final Count Down",
        "description" => "If your health is above 50%: damage reduction increased by 20.0%",
        "tree_row_position" => 3,
        "tree_column_position" => 4,
        "tree_name" => "defender",
        "required_ability_id" => "Ability_Sword_FinalStand",
        "icon" => "swordPassive7",
        "slug" => "final-count-down-09f5c8",
        "cooldown_id" => "",
        "parsed_description" => "If your health is above 50%: damage reduction increased by 20.0%",
        "cooldown_time" => nil,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/swordpassive7.png"
      }, 
      {
        "id" => 1070,
        "weapon_tag" => "Sword",
        "ability_type" => "passive",
        "ability_id" => "Passive_Sword_Defender_CDRWhileBlock",
        "name" => "One with the Shield",
        "description" => "When you block with a shield all shield skills recharge 1.0%.",
        "tree_row_position" => 2,
        "tree_column_position" => 1,
        "tree_name" => "defender",
        "required_ability_id" => "",
        "icon" => "Rapier_Ability1Mod1_Pressure",
        "slug" => "one-with-the-shield-c2a168",
        "cooldown_id" => "",
        "parsed_description" => "When you block with a shield all shield skills recharge 1.0%.",
        "cooldown_time" => nil,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/rapier_ability1mod1_pressure.png"
      }, 
      {
        "id" => 1057,
        "weapon_tag" => "Sword",
        "ability_type" => "upgrade",
        "ability_id" => "Upgrade_Sword_Bash_Dmg",
        "name" => "Intimidating Bash",
        "description" => "Shield bash causes greatly increase threat and 100% more damage.",
        "tree_row_position" => 2,
        "tree_column_position" => 0,
        "tree_name" => "defender",
        "required_ability_id" => "Ability_Sword_Bash",
        "icon" => "warhammerAbility3_mod1",
        "slug" => "intimidating-bash-8760a4",
        "cooldown_id" => "",
        "parsed_description" => "Shield bash causes greatly increase threat and 100% more damage.",
        "cooldown_time" => nil,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/warhammerability3_mod1.png"
      }, 
      {
        "id" => 1059,
        "weapon_tag" => "Sword",
        "ability_type" => "active",
        "ability_id" => "Ability_Sword_Rush",
        "name" => "Shield Rush",
        "description" => "Rush forward 5 meters knocking back foes and dealing 125.4% weapon damage.",
        "tree_row_position" => 0,
        "tree_column_position" => 2,
        "tree_name" => "defender",
        "required_ability_id" => "",
        "icon" => "swordAbility5",
        "slug" => "shield-rush-f71c84",
        "cooldown_id" => "Ability_Sword_Rush",
        "parsed_description" => "Rush forward 5 meters knocking back foes and dealing 125.4% weapon damage.",
        "cooldown_time" => 20,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/swordability5.png"
      }, 
      {
        "id" => 1060,
        "weapon_tag" => "Sword",
        "ability_type" => "upgrade",
        "ability_id" => "Upgrade_Sword_Rush_Weak",
        "name" => "Improved Rush",
        "description" => "On successful hit all enemies within 5m gain 10.0% Weaken for 4.0s. (Weaken reduces damage.)",
        "tree_row_position" => 2,
        "tree_column_position" => 2,
        "tree_name" => "defender",
        "required_ability_id" => "Ability_Sword_Rush",
        "icon" => "GreatAxe_Ability5_Maelstrom",
        "slug" => "improved-rush-40fdfe",
        "cooldown_id" => "",
        "parsed_description" => "On successful hit all enemies within 5m gain 10.0% Weaken for 4.0s. (Weaken reduces damage.)",
        "cooldown_time" => nil,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/greataxe_ability5_maelstrom.png"
      }, 
      {
        "id" => 1061,
        "weapon_tag" => "Sword",
        "ability_type" => "upgrade",
        "ability_id" => "Upgrade_Sword_Rush_Slow",
        "name" => "Intimidating Rush",
        "description" => "On successful hit all enemies within 5m of you are 30.0% Slowed for 4.0s. (Slow reduces movement speed.)",
        "tree_row_position" => 4,
        "tree_column_position" => 2,
        "tree_name" => "defender",
        "required_ability_id" => "Ability_Sword_Rush",
        "icon" => "swordAbility5_mod1",
        "slug" => "intimidating-rush-21e648",
        "cooldown_id" => "",
        "parsed_description" => "On successful hit all enemies within 5m of you are 30.0% Slowed for 4.0s. (Slow reduces movement speed.)",
        "cooldown_time" => nil,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/swordability5_mod1.png"
      }, 
      {
        "id" => 1062,
        "weapon_tag" => "Sword",
        "ability_type" => "active",
        "ability_id" => "Ability_Sword_FinalStand",
        "name" => "Defiant Stance",
        "description" => "For 8s, reduce the incoming base damage from attackers by 30.0%. <br/> <br/>Taunt Gem Compatible: If you have a Carnelian gem equiped in your sword, This ability cause an 6s taunt to all enemies within 8m. (Taunt causes monsters to focus only on you.)",
        "tree_row_position" => 2,
        "tree_column_position" => 4,
        "tree_name" => "defender",
        "required_ability_id" => "",
        "icon" => "swordAbility6",
        "slug" => "defiant-stance-b67dc0",
        "cooldown_id" => "Ability_Sword_FinalStand",
        "parsed_description" => "For 8s, reduce the incoming base damage from attackers by 30.0%. <br/> <br/>Taunt Gem Compatible: If you have a Carnelian gem equiped in your sword, This ability cause an 6s taunt to all enemies within 8m. (Taunt causes monsters to focus only on you.)",
        "cooldown_time" => 45,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/swordability6.png"
      }, 
      {
        "id" => 1065,
        "weapon_tag" => "Sword",
        "ability_type" => "passive",
        "ability_id" => "Passive_Sword_Defender_Armor",
        "name" => "Sturdy Shield",
        "description" => "Grants an additional 15.0% physical armor.",
        "tree_row_position" => 0,
        "tree_column_position" => 1,
        "tree_name" => "defender",
        "required_ability_id" => "",
        "icon" => "swordPassive14",
        "slug" => "sturdy-shield-524030",
        "cooldown_id" => "",
        "parsed_description" => "Grants an additional 15.0% physical armor.",
        "cooldown_time" => nil,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/swordpassive14.png"
      }, 
      {
        "id" => 1067,
        "weapon_tag" => "Sword",
        "ability_type" => "passive",
        "ability_id" => "Passive_Sword_Defender_EleArmor",
        "name" => "Elemental Resistance",
        "description" => "Reduce damage from all magical types by 10.0%.",
        "tree_row_position" => 1,
        "tree_column_position" => 1,
        "tree_name" => "defender",
        "required_ability_id" => "",
        "icon" => "swordPassive11",
        "slug" => "elemental-resistance-e7afaa",
        "cooldown_id" => "",
        "parsed_description" => "Reduce damage from all magical types by 10.0%.",
        "cooldown_time" => nil,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/swordpassive11.png"
      }, 
      {
        "id" => 1068,
        "weapon_tag" => "Sword",
        "ability_type" => "passive",
        "ability_id" => "Passive_Sword_Defender_FortWhileBlock",
        "name" => "Defensive Training",
        "description" => "When you block an attack gain 10.0% Fortify for 5.0s.",
        "tree_row_position" => 1,
        "tree_column_position" => 3,
        "tree_name" => "defender",
        "required_ability_id" => "",
        "icon" => "warhammerAbility1_mod1",
        "slug" => "defensive-training-8245bb",
        "cooldown_id" => "",
        "parsed_description" => "When you block an attack gain 10.0% Fortify for 5.0s.",
        "cooldown_time" => nil,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/warhammerability1_mod1.png"
      }, 
      {
        "id" => 1071,
        "weapon_tag" => "Sword",
        "ability_type" => "passive",
        "ability_id" => "Passive_Sword_Defender_DmgOnFinal",
        "name" => "Final Blow",
        "description" => "The 3rd attack in your light attack deals 15.0% more damage and cause more threat.",
        "tree_row_position" => 3,
        "tree_column_position" => 1,
        "tree_name" => "defender",
        "required_ability_id" => "",
        "icon" => "SwordAbility3_mod2",
        "slug" => "final-blow-85eaa3",
        "cooldown_id" => "",
        "parsed_description" => "The 3rd attack in your light attack deals 15.0% more damage and cause more threat.",
        "cooldown_time" => nil,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/swordability3_mod2.png"
      }, 
      {
        "id" => 1073,
        "weapon_tag" => "Sword",
        "ability_type" => "passive",
        "ability_id" => "Passive_Sword_Defender_HealBoost",
        "name" => "Recuperation",
        "description" => "All incoming healing and regeneration increased by 10.0%.",
        "tree_row_position" => 4,
        "tree_column_position" => 3,
        "tree_name" => "defender",
        "required_ability_id" => "",
        "icon" => "swordPassive13",
        "slug" => "recuperation-28f8d5",
        "cooldown_id" => "",
        "parsed_description" => "All incoming healing and regeneration increased by 10.0%.",
        "cooldown_time" => nil,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/swordpassive13.png"
      }, 
      {
        "id" => 1074,
        "weapon_tag" => "Sword",
        "ability_type" => "passive",
        "ability_id" => "Ultimate_Sword_Defender",
        "name" => "Defensive Formation",
        "description" => "While blocking reduce damage to all allies within 2 meters by 30.0%. (1s cooldown)",
        "tree_row_position" => 5,
        "tree_column_position" => 2,
        "tree_name" => "defender",
        "required_ability_id" => "",
        "icon" => "firestaffAbility3_mod2",
        "slug" => "defensive-formation-304daa",
        "cooldown_id" => "",
        "parsed_description" => "While blocking reduce damage to all allies within 2 meters by 30.0%. (1s cooldown)",
        "cooldown_time" => nil,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/firestaffability3_mod2.png"
      }, 
      {
        "id" => 1072,
        "weapon_tag" => "Sword",
        "ability_type" => "passive",
        "ability_id" => "Passive_Sword_Defender_MaxHp",
        "name" => "Fortitude",
        "description" => "While holding a Sword current and max health are increased by 10.0%.",
        "tree_row_position" => 3,
        "tree_column_position" => 3,
        "tree_name" => "defender",
        "required_ability_id" => "",
        "icon" => "swordPassive9",
        "slug" => "fortitude-8cf81c",
        "cooldown_id" => "",
        "parsed_description" => "While holding a Sword current and max health are increased by 10.0%.",
        "cooldown_time" => nil,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/swordpassive9.png"
      }, 
      {
        "id" => 1069,
        "weapon_tag" => "Sword",
        "ability_type" => "passive",
        "ability_id" => "Passive_Sword_Defender_RngBlock",
        "name" => "High Grip",
        "description" => "Stamina damage is reduced by 15.0% when blocking a ranged attack with a shield.",
        "tree_row_position" => 1,
        "tree_column_position" => 4,
        "tree_name" => "defender",
        "required_ability_id" => "",
        "icon" => "swordPassive8",
        "slug" => "high-grip-a99586",
        "cooldown_id" => "",
        "parsed_description" => "Stamina damage is reduced by 15.0% when blocking a ranged attack with a shield.",
        "cooldown_time" => nil,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/swordpassive8.png"
      }
    ], 
    "swordmaster" => [
      {
        "id" => 1049,
        "weapon_tag" => "Sword",
        "ability_type" => "passive",
        "ability_id" => "Passive_Sword_Swordmaster_RemoveOnHeavy",
        "name" => "Freeing Justice",
        "description" => "Successfully hitting with a Heavy attack cause you to lose 1 debuff.",
        "tree_row_position" => 1,
        "tree_column_position" => 3,
        "tree_name" => "swordmaster",
        "required_ability_id" => "",
        "icon" => "GreatAxe_Ability4Pass2_FatalAttraction",
        "slug" => "freeing-justice-56d662",
        "cooldown_id" => "",
        "parsed_description" => "Successfully hitting with a Heavy attack cause you to lose 1 debuff.",
        "cooldown_time" => nil,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/greataxe_ability4pass2_fatalattraction.png"
      }, {
        "id" => 1047,
        "weapon_tag" => "Sword",
        "ability_type" => "passive",
        "ability_id" => "Passive_Sword_Swordmaster_SlowOnFinal",
        "name" => "Achilles Heel",
        "description" => "The final attack in your light attack chain causes a 20.0% Slow for 2.0s. (Slow reduces movement speed.)",
        "tree_row_position" => 0,
        "tree_column_position" => 4,
        "tree_name" => "swordmaster",
        "required_ability_id" => "",
        "icon" => "warhammerAbility2_mod2",
        "slug" => "achilles-heel-ceb790",
        "cooldown_id" => "",
        "parsed_description" => "The final attack in your light attack chain causes a 20.0% Slow for 2.0s. (Slow reduces movement speed.)",
        "cooldown_time" => nil,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/warhammerability2_mod2.png"
      }
    ]
  }, 
  "weapon2_ability_trees" => {
    "juggernaut" => [
      {
        "id" => 1075,
        "weapon_tag" => "WarHammer",
        "ability_type" => "active",
        "ability_id" => "Ability_Warhammer_ArmorBreaker",
        "name" => "Armor Breaker",
        "description" => "A Powerful swing that penetrates 35.0% of the Target's armor and deals 140.0% Weapon damage.",
        "tree_row_position" => 0,
        "tree_column_position" => 0,
        "tree_name" => "juggernaut",
        "required_ability_id" => "",
        "icon" => "warhammerAbility1",
        "slug" => "armor-breaker-b04817",
        "cooldown_id" => "Ability_WarHammer_ArmorBreaker",
        "parsed_description" => "A Powerful swing that penetrates 35.0% of the Target's armor and deals 140.0% Weapon damage.",
        "cooldown_time" => 12,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/warhammerability1.png"
      }, 
      {
        "id" => 1076,
        "weapon_tag" => "WarHammer",
        "ability_type" => "upgrade",
        "ability_id" => "Upgrade_WarHammer_ArmBreak_Grit",
        "name" => "Indomitable",
        "description" => "Adds Grit to the attack, making the attack unstoppable.",
        "tree_row_position" => 1,
        "tree_column_position" => 0,
        "tree_name" => "juggernaut",
        "required_ability_id" => "Ability_Warhammer_ArmorBreaker",
        "icon" => "warhammerAbility1_mod1",
        "slug" => "indomitable-1e6d7b",
        "cooldown_id" => "Ability_WarHammer_ArmorBreaker",
        "parsed_description" => "Adds Grit to the attack, making the attack unstoppable.",
        "cooldown_time" => nil,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/warhammerability1_mod1.png"
      }, 
      {
        "id" => 1077,
        "weapon_tag" => "WarHammer",
        "ability_type" => "upgrade",
        "ability_id" => "Upgrade_WarHammer_ArmBreak_Rend",
        "name" => "Lasting Trauma",
        "description" => "Armor Breaker grants the targets Rend, reducing damage absorption by 15.0% for 10.0 seconds.",
        "tree_row_position" => 2,
        "tree_column_position" => 0,
        "tree_name" => "juggernaut",
        "required_ability_id" => "Upgrade_WarHammer_ArmBreak_Grit",
        "icon" => "Spear_Perforate_BonusRend",
        "slug" => "lasting-trauma-75ec5d",
        "cooldown_id" => "Ability_WarHammer_ArmorBreaker",
        "parsed_description" => "Armor Breaker grants the targets Rend, reducing damage absorption by 15.0% for 10.0 seconds.",
        "cooldown_time" => nil,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/spear_perforate_bonusrend.png"
      }, 
      {
        "id" => 1092,
        "weapon_tag" => "WarHammer",
        "ability_type" => "passive",
        "ability_id" => "Passive_WarHammer_Juggernaut_CDROnHit",
        "name" => "Quick Recovery",
        "description" => "Cooldowns are reduced by 7% with Heavy attacks.",
        "tree_row_position" => 3,
        "tree_column_position" => 1,
        "tree_name" => "juggernaut",
        "required_ability_id" => "",
        "icon" => "warhammerAbility2_mod4",
        "slug" => "quick-recovery-48afe3",
        "cooldown_id" => "",
        "parsed_description" => "Cooldowns are reduced by 7% with Heavy attacks.",
        "cooldown_time" => nil,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/warhammerability2_mod4.png"
      }, 
      {
        "id" => 1089,
        "weapon_tag" => "WarHammer",
        "ability_type" => "passive",
        "ability_id" => "Passive_WarHammer_Juggernaut_ExhaustOnHit",
        "name" => "Exhaustive Attacks",
        "description" => "All Warhammer abilities apply Exhaust, slowing target's stamina regeneration by 15.0% for 5.0 seconds. (Does not stack)",
        "tree_row_position" => 1,
        "tree_column_position" => 1,
        "tree_name" => "juggernaut",
        "required_ability_id" => "",
        "icon" => "warhammerAbility1_mod1",
        "slug" => "exhaustive-attacks-1eaeb9",
        "cooldown_id" => "",
        "parsed_description" => "All Warhammer abilities apply Exhaust, slowing target's stamina regeneration by 15.0% for 5.0 seconds. (Does not stack)",
        "cooldown_time" => nil,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/warhammerability1_mod1.png"
      }, 
      {
        "id" => 1090,
        "weapon_tag" => "WarHammer",
        "ability_type" => "passive",
        "ability_id" => "Passive_WarHammer_Juggernaut_HeavyGrit",
        "name" => "Hardened Steel",
        "description" => "Adds Grit to Hammer Heavy Attacks, and grants a 20.0% damage reduction while the Heavy attack Grit is active. <br/><br/>(Grit is an added stagger resistance that stops attacks from being interrupted by reactions)",
        "tree_row_position" => 1,
        "tree_column_position" => 4,
        "tree_name" => "juggernaut",
        "required_ability_id" => "",
        "icon" => "firestaffAbility2_mod1",
        "slug" => "hardened-steel-e9cf8e",
        "cooldown_id" => "",
        "parsed_description" => "Adds Grit to Hammer Heavy Attacks, and grants a 20.0% damage reduction while the Heavy attack Grit is active. <br/><br/>(Grit is an added stagger resistance that stops attacks from being interrupted by reactions)",
        "cooldown_time" => nil,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/firestaffability2_mod1.png"
      }, 
      {
        "id" => 1087,
        "weapon_tag" => "WarHammer",
        "ability_type" => "passive",
        "ability_id" => "Passive_WarHammer_Juggernaut_LightHeavyPenetrate",
        "name" => "Epitome Of Bonk!",
        "description" => "Increase Armor Penetration by 10.0% for all War Hammer Standard attacks.",
        "tree_row_position" => 0,
        "tree_column_position" => 1,
        "tree_name" => "juggernaut",
        "required_ability_id" => "",
        "icon" => "MusketPassive11",
        "slug" => "epitome-of-bonk-e0eea8",
        "cooldown_id" => "",
        "parsed_description" => "Increase Armor Penetration by 10.0% for all War Hammer Standard attacks.",
        "cooldown_time" => nil,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/musketpassive11.png"
      }
    ], 
    "crowd crusher" => [
      {
        "id" => 1100,
        "weapon_tag" => "WarHammer",
        "ability_type" => "upgrade",
        "ability_id" => "Upgrade_WarHammer_Shockwave_SizeIncrease",
        "name" => "Meteoric Crater",
        "description" => "Expands the effective range of the Shockwave to a 4.0 meter radius.",
        "tree_row_position" => 3,
        "tree_column_position" => 0,
        "tree_name" => "crowd crusher",
        "required_ability_id" => "Upgrade_WarHammer_Shockwave_Weaken",
        "icon" => "warhammerAbility5_mod2",
        "slug" => "meteoric-crater-a5af97",
        "cooldown_id" => "Ability_WarHammer_Shockwave",
        "parsed_description" => "Expands the effective range of the Shockwave to a 4.0 meter radius.",
        "cooldown_time" => nil,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/warhammerability5_mod2.png"
      }, 
      {
        "id" => 1102,
        "weapon_tag" => "WarHammer",
        "ability_type" => "upgrade",
        "ability_id" => "Upgrade_WarHammer_PathOfDestiny_Stagger",
        "name" => "Seismic Waves",
        "description" => "Path of Destiny now staggers all targets in its path.",
        "tree_row_position" => 3,
        "tree_column_position" => 4,
        "tree_name" => "crowd crusher",
        "required_ability_id" => "Ability_WarHammer_PathOfDestiny",
        "icon" => "warhammerAbility4_mod2",
        "slug" => "seismic-waves-000767",
        "cooldown_id" => "Ability_WarHammer_PathOfDestiny",
        "parsed_description" => "Path of Destiny now staggers all targets in its path.",
        "cooldown_time" => nil,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/warhammerability4_mod2.png"
      }, 
      {
        "id" => 1103,
        "weapon_tag" => "WarHammer",
        "ability_type" => "upgrade",
        "ability_id" => "Upgrade_WarHammer_PathOfDestiny_CDRPerHit",
        "name" => "Stimulated Reduction",
        "description" => "Ability cooldown reduced by 5.0% for each enemy hit with Path of Destiny.",
        "tree_row_position" => 4,
        "tree_column_position" => 4,
        "tree_name" => "crowd crusher",
        "required_ability_id" => "Upgrade_WarHammer_PathOfDestiny_Stagger",
        "icon" => "warhammerAbility2_mod4",
        "slug" => "stimulated-reduction-2c422c",
        "cooldown_id" => "Ability_WarHammer_PathOfDestiny",
        "parsed_description" => "Ability cooldown reduced by 5.0% for each enemy hit with Path of Destiny.",
        "cooldown_time" => nil,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/warhammerability2_mod4.png"
      }, 
      {
        "id" => 1110,
        "weapon_tag" => "WarHammer",
        "ability_type" => "passive",
        "ability_id" => "Passive_WarHammer_CrowdCrusher_HPOnCCHit",
        "name" => "Prevailing Spirit",
        "description" => "Regain 35.0% of damage dealt as Health when using a Crowd Crusher ability.",
        "tree_row_position" => 3,
        "tree_column_position" => 3,
        "tree_name" => "crowd crusher",
        "required_ability_id" => "",
        "icon" => "swordPassive10",
        "slug" => "prevailing-spirit-6b30d7",
        "cooldown_id" => "",
        "parsed_description" => "Regain 35.0% of damage dealt as Health when using a Crowd Crusher ability.",
        "cooldown_time" => nil,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/swordpassive10.png"
      }, 
      {
        "id" => 1099,
        "weapon_tag" => "WarHammer",
        "ability_type" => "upgrade",
        "ability_id" => "Upgrade_WarHammer_Shockwave_Weaken",
        "name" => "Frailty",
        "description" => "The trauma of the attack causes Weaken, decreasing the damage dealt from the target's attacks by 10.0% for 10.0 seconds.",
        "tree_row_position" => 2,
        "tree_column_position" => 0,
        "tree_name" => "crowd crusher",
        "required_ability_id" => "Ability_WarHammer_Shockwave",
        "icon" => "warhammerAbility5_mod1",
        "slug" => "frailty-d7a625",
        "cooldown_id" => "Ability_WarHammer_Shockwave",
        "parsed_description" => "The trauma of the attack causes Weaken, decreasing the damage dealt from the target's attacks by 10.0% for 10.0 seconds.",
        "cooldown_time" => nil,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/warhammerability5_mod1.png"
      }, 
      {
        "id" => 1101,
        "weapon_tag" => "WarHammer",
        "ability_type" => "active",
        "ability_id" => "Ability_WarHammer_PathOfDestiny",
        "name" => "Path Of Destiny",
        "description" => "A powerful ground strike that erupts a linear wave of energy in front of the player, dealing 110.0% weapon damage to all targets in its path.",
        "tree_row_position" => 2,
        "tree_column_position" => 4,
        "tree_name" => "crowd crusher",
        "required_ability_id" => "",
        "icon" => "warhammerAbility4",
        "slug" => "path-of-destiny-fc7278",
        "cooldown_id" => "Ability_WarHammer_PathOfDestiny",
        "parsed_description" => "A powerful ground strike that erupts a linear wave of energy in front of the player, dealing 110.0% weapon damage to all targets in its path.",
        "cooldown_time" => 22,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/warhammerability4.png"
      }, 
      {
        "id" => 1105,
        "weapon_tag" => "WarHammer",
        "ability_type" => "passive",
        "ability_id" => "Passive_WarHammer_CrowdCrusher_LessStaminaOnBlock",
        "name" => "I Can Do This All Day",
        "description" => "Reduce Stamina consumption by -30.0% when Blocking Melee Attacks.",
        "tree_row_position" => 0,
        "tree_column_position" => 3,
        "tree_name" => "crowd crusher",
        "required_ability_id" => "",
        "icon" => "Spear_VaultKick_EmpowerOnBlockBreak",
        "slug" => "i-can-do-this-all-day-b8d315",
        "cooldown_id" => "",
        "parsed_description" => "Reduce Stamina consumption by -30.0% when Blocking Melee Attacks.",
        "cooldown_time" => nil,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/spear_vaultkick_empoweronblockbreak.png"
      }, 
      {
        "id" => 1104,
        "weapon_tag" => "WarHammer",
        "ability_type" => "passive",
        "ability_id" => "Passive_WarHammer_CrowdCrusher_ArmorPerNearbyEnemy",
        "name" => "Outnumbered",
        "description" => "Increase damage absorption by 10.0% if surrounded by 2 or more enemies within 5.0 meters of player.",
        "tree_row_position" => 0,
        "tree_column_position" => 1,
        "tree_name" => "crowd crusher",
        "required_ability_id" => "",
        "icon" => "warhammerAbility2",
        "slug" => "outnumbered-0b20a6",
        "cooldown_id" => "",
        "parsed_description" => "Increase damage absorption by 10.0% if surrounded by 2 or more enemies within 5.0 meters of player.",
        "cooldown_time" => nil,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/warhammerability2.png"
      }, 
      {
        "id" => 1107,
        "weapon_tag" => "WarHammer",
        "ability_type" => "passive",
        "ability_id" => "Passive_WarHammer_CrowdCrusher_CDROnDebuffHit",
        "name" => "Acceleration",
        "description" => "Reduce War Hammer Cooldowns by 7.0% when using light attacks against targets with an active Debuff.",
        "tree_row_position" => 1,
        "tree_column_position" => 4,
        "tree_name" => "crowd crusher",
        "required_ability_id" => "",
        "icon" => "warhammerAbility2_mod4",
        "slug" => "acceleration-355f75",
        "cooldown_id" => "",
        "parsed_description" => "Reduce War Hammer Cooldowns by 7.0% when using light attacks against targets with an active Debuff.",
        "cooldown_time" => nil,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/warhammerability2_mod4.png"
      }, 
      {
        "id" => 1108,
        "weapon_tag" => "WarHammer",
        "ability_type" => "passive",
        "ability_id" => "Passive_WarHammer_CrowdCrusher_HasteOnDebuff",
        "name" => "Facilitated Expedition",
        "description" => "After hitting a target with an active Debuff; Obtain Haste, increasing movement speed by 15.0% for 3.0 seconds.",
        "tree_row_position" => 2,
        "tree_column_position" => 1,
        "tree_name" => "crowd crusher",
        "required_ability_id" => "",
        "icon" => "warhammerAbility3_mod3",
        "slug" => "facilitated-expedition-3dd78d",
        "cooldown_id" => "",
        "parsed_description" => "After hitting a target with an active Debuff; Obtain Haste, increasing movement speed by 15.0% for 3.0 seconds.",
        "cooldown_time" => nil,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/warhammerability3_mod3.png"
      }, 
      {
        "id" => 1112,
        "weapon_tag" => "WarHammer",
        "ability_type" => "passive",
        "ability_id" => "Ult_Passive_WarHammer_SlowOnCC",
        "name" => "Aftershock",
        "description" => "Whenever a target is affected by a Crowd Control effect, they are slowed by 20.0% for 4.0 Seconds.",
        "tree_row_position" => 5,
        "tree_column_position" => 2,
        "tree_name" => "crowd crusher",
        "required_ability_id" => "",
        "icon" => "warhammerAbility4_mod2",
        "slug" => "aftershock-d27c1d",
        "cooldown_id" => "",
        "parsed_description" => "Whenever a target is affected by a Crowd Control effect, they are slowed by 20.0% for 4.0 Seconds.",
        "cooldown_time" => nil,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/warhammerability4_mod2.png"
      }, 
      {
        "id" => 1098,
        "weapon_tag" => "WarHammer",
        "ability_type" => "active",
        "ability_id" => "Ability_WarHammer_Shockwave",
        "name" => "Shockwave",
        "description" => "Slam the Hammer into the ground causing a 3.0 meter radius AOE earthquake that deals 80.0% weapon damage. Applies Stun to all impacted targets for 2.0 Seconds. <br/> <br/>Taunt Gem Compatible: If you have a Carnelian gem equiped in your war hammer, This ability cause a 6.0s taunts when it hits. (Taunt causes monsters to focus only on you.)",
        "tree_row_position" => 1,
        "tree_column_position" => 0,
        "tree_name" => "crowd crusher",
        "required_ability_id" => "",
        "icon" => "warhammerAbility5",
        "slug" => "shockwave-2a84ed",
        "cooldown_id" => "Ability_WarHammer_Shockwave",
        "parsed_description" => "Slam the Hammer into the ground causing a 3.0 meter radius AOE earthquake that deals 80.0% weapon damage. Applies Stun to all impacted targets for 2.0 Seconds. <br/> <br/>Taunt Gem Compatible: If you have a Carnelian gem equiped in your war hammer, This ability cause a 6.0s taunts when it hits. (Taunt causes monsters to focus only on you.)",
        "cooldown_time" => 20,
        "asset_path" => "https://cdn.newworldfans.com/db_images/db/abilities/warhammerability5.png"
      }
    ]
  }, 
  "description_html" => nil
}